title: ycra.dev
email: ycra.dev@gmail.com
baseurl: ""
url: "https://ycra-dev.github.io"
github_username:  ycra-dev

theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

show_excerpts: true
timezone: Asia/Seoul
lang: ko-KR
permalink: /:categories/:title/

header_pages:
  - categories.md
  - about.md